version: "3.9"
    
services:

  wordpress:
    container_name: w1.doo.ovh 
    image: devsops:2
    ports:
      - 220:222
      - 8888:80    

    volumes:
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh

    networks:
      - proxy

volumes:
  devops1_db: {}

networks:
  proxy:
    name: proxy

